# Generated by Django 4.2.6 on 2023-11-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="events/")),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name_plural": "events",
                "ordering": ["-id"],
            },
        ),
    ]
