# Generated by Django 4.2.6 on 2023-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
