# Generated by Django 4.2.6 on 2023-11-08 15:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
