# Generated by Django 4.2.6 on 2023-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_gallery_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="popup_id",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
