# Generated by Django 4.2.6 on 2023-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_gallery_popup_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newsletter",
        ),
    ]
