# Generated by Django 3.2.1 on 2023-12-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_event_image_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name_plural': 'teams'},
        ),
    ]
