# Generated by Django 3.2.1 on 2023-12-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Appointments'},
        ),
    ]
