# Generated by Django 3.2.1 on 2023-12-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id'], 'verbose_name_plural': 'banners'},
        ),
    ]
